import "./globals.css";
import { Rubik } from "next/font/google";

export const dynamic = "force-dynamic";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="w-full h-screen">
          <header className="p-2">
            <p className="bg-primary h-12 w-12 rounded-full"></p>
          </header>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
